// Generated by CIRCT unknown git version
module fir_optimized(	// step7_comb.mlir:2:3
  input  [15:0] delay0,	// step7_comb.mlir:2:31
                delay1,	// step7_comb.mlir:2:49
                delay2,	// step7_comb.mlir:2:67
  output [15:0] result	// step7_comb.mlir:2:86
);

  assign result = delay0 + (delay1 << 16'h1) + delay2;	// step7_comb.mlir:3:15, :4:10, :5:10, :6:10, :7:5
endmodule

module {
  hw.module @fir_optimized(in %delay0 : i16, in %delay1 : i16, in %delay2 : i16, out result : i16) {
    %c1_i16 = hw.constant 1 : i16
    %0 = comb.shl %delay1, %c1_i16 : i16
    %1 = comb.add %delay0, %0 : i16
    %2 = comb.add %1, %delay2 : i16
    hw.output %2 : i16
  }
}

