// Generated by CIRCT unknown git version
module fir_simple_optimized(	// temp_comb.mlir:2:3
  input  [15:0] delay0,	// temp_comb.mlir:2:38
                delay1,	// temp_comb.mlir:2:56
                delay2,	// temp_comb.mlir:2:74
  output [15:0] result	// temp_comb.mlir:2:93
);

  assign result = delay0 + (delay1 << 16'h1) + delay2;	// temp_comb.mlir:3:15, :4:10, :5:10, :6:10, :7:5
endmodule

module {
  hw.module @fir_simple_optimized(in %delay0 : i16, in %delay1 : i16, in %delay2 : i16, out result : i16) {
    %c1_i16 = hw.constant 1 : i16
    %0 = comb.shl %delay1, %c1_i16 : i16
    %1 = comb.add %delay0, %0 : i16
    %2 = comb.add %1, %delay2 : i16
    hw.output %2 : i16
  }
}

