// Generated by CIRCT unknown git version
module fir_input(	// step7_comb.mlir:2:3
  input  [15:0] arg0,	// step7_comb.mlir:2:27
                arg1,	// step7_comb.mlir:2:43
                arg2,	// step7_comb.mlir:2:59
  output [15:0] result	// step7_comb.mlir:2:76
);

  assign result = arg0 + (arg1 << 16'h1) + arg2;	// step7_comb.mlir:3:15, :4:10, :5:10, :6:10, :7:5
endmodule

module {
  hw.module @fir_input(in %arg0 : i16, in %arg1 : i16, in %arg2 : i16, out result : i16) {
    %c1_i16 = hw.constant 1 : i16
    %0 = comb.shl %arg1, %c1_i16 : i16
    %1 = comb.add %arg0, %0 : i16
    %2 = comb.add %1, %arg2 : i16
    hw.output %2 : i16
  }
}

